FROM ruby:3.0.2

RUN useradd -m -u 1000 -g staff docker && echo "root:1234" | chpasswd

ENV INSTALL_PATH /opt/app
RUN mkdir -p $INSTALL_PATH

RUN gem install rails bundler
RUN chown -R docker:staff $INSTALL_PATH
WORKDIR $INSTALL_PATH

USER docker:staff
CMD ["/bin/sh"]
