version: '3'

services:
  mysql:
    image: mysql
    container_name: mysql
    entrypoint: ['docker-entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password

  payment_api:
    container_name: payment_api
    tty: true
    stdin_open: true
    build: $PWD/../projects/payment_api
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - $PWD/../projects/payment_api:/var/www/app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - kafka

  order_api:
    container_name: order_api
    tty: true
    stdin_open: true
    build: $PWD/../projects/order_api
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - $PWD/../projects/order_api:/var/www/app
    ports:
      - "5000:3000"
    depends_on:
      - mysql
      - kafka

  account_api:
    container_name: account_api
    tty: true
    stdin_open: true
    build: $PWD/../projects/account_api
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - $PWD/../projects/account_api:/var/www/app
    ports:
      - "6000:3000"
    depends_on:
      - mysql
      - kafka

  receivable_api:
    container_name: receivable_api
    tty: true
    stdin_open: true
    build: $PWD/../projects/receivable_api
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - $PWD/../projects/receivable_api:/var/www/app
    ports:
      - "7000:3000"
    depends_on:
      - mysql
      - kafka

  redis:
    image: redis

  zookeeper:
    container_name: 'zookeeper'
    image: 'bitnami/zookeeper:latest'
    labels:
      dns: 'zookeeper'
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    tmpfs: "/datalog"

  kafka:
    container_name: 'kafka'
    image: 'bitnami/kafka:latest'
    labels:
      dns: 'kafka'
    ports:
      - "9092:9092"
      - '9093:9093'
    environment:
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=10.120.15.2:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://10.120.15.1:9092,EXTERNAL://10.120.15.1:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
